// generated by bin/generation.py
DECL_IR_TOK( info )
DECL_IR_TOK( syscall )
DECL_IR_TOK( set_base_size_and_alig )
DECL_IR_TOK( set_RawRef_dependancy )
DECL_IR_TOK( reassign_rec )
DECL_IR_TOK( set_ptr_val )
