// Generated by CoffeeScript 1.4.0
var Model;

Model = (function() {

  Model.__counter = 0;

  Model.__modlist = [];

  Model.__n_views = {};

  Model.__timeout = void 0;

  Model.__force_m = false;

  Model.__id_map = new WeakMap();

  Model.__cur_id = 1;

  function Model(__ptr, parent) {
    this.__ptr = __ptr != null ? __ptr : asm_mod.allocate(1);
    if (parent != null) {
      this.__parent = parent;
    }
  }

  Object.defineProperty(Model.prototype, "attr_names", {
    get: function() {
      return [];
    }
  });

  Model.prototype.bind = function(view) {
    var views;
    views = this.__container.__views;
    if (views.indexOf(view) < 0) {
      return views.push(view);
    }
  };

  Object.defineProperty(Model.prototype, "__container", {
    get: function() {
      if (this.parent != null) {
        return this.parent.__container;
      } else {
        this.__add_mv_attr();
        return this;
      }
    }
  });

  Model.prototype.__add_mv_attr = function(view) {
    if (this.__views != null) {
      return;
    }
    this.__views = [];
    this.__id = 0;
    return this.__date_last_modification = 0;
  };

  return Model;

})();
